# Generated by Django 4.2.30 on 2026-09-26 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_order_alter_blog_posted_alter_comment_date_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2026, 9, 26, 14, 52, 30, 269641), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 26, 14, 52, 30, 269641), verbose_name='Дата добавления'),
        ),
    ]
