# Generated by Django 6.0.2 on 2026-05-16 21:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0007_alter_blog_posted_alter_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2026, 5, 17, 0, 27, 17, 173209), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='catalog/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 17, 0, 27, 17, 173830), verbose_name='Дата добавления'),
        ),
    ]
