# Generated by Django 4.2.30 on 2026-09-26 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0003_alter_blog_posted_alter_comment_date'),
        ('auto', '0008_alter_blog_posted_alter_catalogitem_image_and_more'),
    ]

    operations = [
    ]
